import {useState} from 'react'
import Link from 'next/link'
import Head from 'next/head'
import {TbPokeball} from 'react-icons/tb'
import {GiHamburgerMenu} from 'react-icons/gi'
import {AiOutlineClose} from 'react-icons/ai'
import Cart from './cart'

const Header = () => {
    const [toggleMenu, setToggleMenu] = useState<boolean>(false);

    return (
        <>
            <Head>
            <title>PokEcommerce</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <header className={toggleMenu ? 'header-wrap-mobile' : 'header-wrap'}>
                <div className='content-wrap'>
                    <div className='menu-wrap' onClick={() => { toggleMenu? setToggleMenu(false) : setToggleMenu(true)}}>
                        <GiHamburgerMenu className={toggleMenu? 'menu-icon-hide' : 'menu-icon'} />
                        <AiOutlineClose className={toggleMenu? 'menu-icon' : 'menu-icon-hide'} />
                    </div>

                    <div className='logo-wrap'>
                        <Link href='/'>
                            <TbPokeball className='logo' />
                        </Link>
                    </div>

                    <div className='bg-block' onClick={() => { toggleMenu? setToggleMenu(false) : setToggleMenu(true)}}></div>

                    <nav className='nav-bar'>
                        <Link href='/' className='nav-link'>Home</Link>
                        <Link href='/products/1' className='nav-link'>Products</Link>
                        <Link href='/' className='nav-link'>About</Link>
                    </nav>
                    
                    <Cart />
                </div>
            </header>
        </>
    );
};

export default Header;
